namespace DevTemWinUi3.Services;

/// <summary>
/// Scaffold-time feature flags for apps generated by
/// <c>dotnet new devtem-winui</c> (--tray/--updates/--database/--http/--health/--crash/--localization/--tests).
/// The double-underscore placeholders are rendered by template replaces:
/// bools become True/False literals, <c>__UPDATES__</c> becomes the selected
/// update value (velopack, basic, or none). Parsed defensively so a scaffold
/// still builds the full app even if a placeholder ever came through
/// unreplaced.
/// Gates UI visibility and layout at runtime, which keeps .xaml free of
/// conditionals (the template engine does not evaluate markers there).
/// </summary>
internal static class AppFeatures
{
    public static readonly bool Tray = ParseFlag("__TRAY__");
    public static readonly string UpdateMode = ParseUpdateMode("__UPDATES__");
    public static readonly bool Updates = UpdateMode != "none";
    public static readonly bool Database = ParseFlag("__DATABASE__");
    public static readonly bool Http = ParseFlag("__HTTP__");
    public static readonly bool Health = ParseFlag("__HEALTH__");
    public static readonly bool Crash = ParseFlag("__CRASH__");
    public static readonly bool Localization = ParseFlag("__LOCALIZATION__");
    public static readonly bool Tests = ParseFlag("__TESTS__");

    private static bool ParseFlag(string raw) =>
        bool.TryParse(raw, out bool value) ? value : true;

    private static string ParseUpdateMode(string raw) => raw switch
    {
        "velopack" or "basic" or "none" => raw,
        "True" => "velopack",
        "False" => "none",
        _ => "velopack",
    };
}
