namespace DevTemWinUi3.Services;

/// <summary>
/// Scaffold-time feature flags for apps generated by
/// <c>dotnet new devtem-winui</c> (--tray/--updates/--database/--http/--health/--crash/--localization/--tests/--distribution/--setup).
/// The double-underscore placeholders are rendered by template replaces:
/// bools become True/False literals, <c>__UPDATES__</c> becomes the selected
/// update value (velopack, basic, none, appinstaller, or store) and
/// <c>__DISTRIBUTION__</c> the distribution (portable or msix).
/// Parsed defensively so a scaffold still builds the full app even if a
/// placeholder ever came through unreplaced.
/// Gates UI visibility and layout at runtime, which keeps .xaml free of
/// conditionals (the template engine does not evaluate markers there).
/// </summary>
internal static class AppFeatures
{
    public static readonly bool Tray = ParseFlag("__TRAY__");
    public static readonly string UpdateMode = ParseUpdateMode("__UPDATES__");
    public static readonly bool Updates = UpdateMode != "none";
    public static readonly bool Database = ParseFlag("__DATABASE__");
    public static readonly bool Http = ParseFlag("__HTTP__");
    public static readonly bool Health = ParseFlag("__HEALTH__");
    public static readonly bool Crash = ParseFlag("__CRASH__");
    public static readonly bool Localization = ParseFlag("__LOCALIZATION__");
    public static readonly bool Tests = ParseFlag("__TESTS__");
    public static readonly string Distribution = ParseDistribution("__DISTRIBUTION__");
    public static readonly bool SetupWizard = ParseFlag("__SETUP__");

    /// <summary>Updates managed outside the app (Store / AppInstaller feed).</summary>
    public static bool IsExternalUpdateMode => UpdateMode is "appinstaller" or "store";

    /// <summary>
    /// Updates the app must not drive itself: scaffold-external modes plus
    /// any packaged run (the install dir is read-only there, so even a
    /// compiled-in Velopack engine can never apply). This is what makes one
    /// binary dual-track: unpackaged it follows the scaffold engine,
    /// packaged it takes the slim status surface.
    /// </summary>
    public static bool IsExternallyManaged => IsExternalUpdateMode || AppInfo.IsPackaged;

    private static bool ParseFlag(string raw) =>
        bool.TryParse(raw, out bool value) ? value : true;

    private static string ParseUpdateMode(string raw) => raw switch
    {
        "velopack" or "basic" or "none" or "appinstaller" or "store" => raw,
        "True" => "velopack",
        "False" => "none",
        _ => "velopack",
    };

    private static string ParseDistribution(string raw) => raw switch
    {
        "portable" or "msix" => raw,
        _ => "portable",
    };
}
