namespace DevTemWinUi3.Services;

/// <summary>
/// Scaffold-time feature flags for apps generated by
/// <c>dotnet new devtem-winui</c> (--tray/--updates/--database/--http/--health).
/// The double-underscore placeholders are rendered as True/False literals by
/// template replaces; parsed defensively so a scaffold still builds the full
/// app even if a placeholder ever came through unreplaced.
/// Gates UI visibility and layout at runtime, which keeps .xaml free of
/// conditionals (the template engine does not evaluate markers there).
/// </summary>
internal static class AppFeatures
{
    public static readonly bool Tray = ParseFlag("__TRAY__");
    public static readonly bool Updates = ParseFlag("__UPDATES__");
    public static readonly bool Database = ParseFlag("__DATABASE__");
    public static readonly bool Http = ParseFlag("__HTTP__");
    public static readonly bool Health = ParseFlag("__HEALTH__");

    private static bool ParseFlag(string raw) =>
        bool.TryParse(raw, out bool value) ? value : true;
}
